plugins {
    id 'java'
    id 'maven-publish'
}

base {
    archivesName = id
    libsDirectory = new File("builtJars/")
}

test {
    useJUnitPlatform()
    dryRun = true
}

java {
    withSourcesJar()
    sourceCompatibility = targetCompatibility = JavaVersion.VERSION_1_8
}

repositories {
    mavenCentral()
}

dependencies {
    // Test dependencies
    testImplementation "org.junit.jupiter:junit-jupiter-engine:${junitVersion}"
    testImplementation "org.mockito:mockito-core:${mockitoVersion}"

    // JSON parsing
    implementation "com.alibaba:fastjson:${fastjsonVersion}"
}

repositories {
    maven {
        url 'https://jitpack.io'
    }
}