plugins {
    id 'java'
    id 'maven-publish'
}

base {
    archivesName = id
}

test {
    useJUnitPlatform()
    dryRun = true
}

java {
    withSourcesJar()
    sourceCompatibility = targetCompatibility = JavaVersion.VERSION_1_8
}

repositories {
    mavenCentral()
    maven {
        url 'https://jitpack.io'
    }
}

dependencies {
    // Test dependencies
    testImplementation "org.junit.jupiter:junit-jupiter-engine:${junitVersion}"
    testImplementation "org.mockito:mockito-core:${mockitoVersion}"

    // JSON parsing
    implementation "com.alibaba:fastjson:${fastjsonVersion}"
}

jar {
    duplicatesStrategy = DuplicatesStrategy.WARN

    manifest {
        attributes "Specification-Title"        : id
        attributes "Specification-Version"      : version
        attributes "Implementation-Title"       : name
        attributes "Implementation-Version"     : version
        attributes "Implementation-Vendor"      : name
        attributes "Implementation-Timestamp"   : new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
    }
}

publishing {
    repositories {
        mavenLocal()
    }
    publications {
        maven(MavenPublication) {
            from components.java

            pom {
                name = 'Java youtube video downloader'
                description = 'Java parser for retrieving YouTube video meta info'
                licenses {
                    license {
                        name = 'The Unlicense'
                        url = 'http://unlicense.org/'
                        distribution = 'repo'
                    }
                }
            }
        }
    }
}

